Update localk8s when container images are updated. (#17)

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -202,3 +202,45 @@ jobs:
         echo "This build is ready for promotion to prod:" > /tmp/body.txt
         echo "IronCoreLabs/deployments#${{ steps.promote-pr.outputs.pr }}" >> /tmp/body.txt
         gh pr comment -F /tmp/body.txt ${{ steps.software-pr.outputs.pr }}
+
+    # Update the local dev clusters to use the new container.
+    - name: Check out depot
+      uses: actions/checkout@v3
+      with:
+        repository: IronCoreLabs/depot
+        path: depot
+        token: ${{ secrets.WORKFLOW_PAT }}
+    - name: Update local dev clusters
+      id: update-depot
+      working-directory: depot/localk8s
+      run: |
+        set -x
+        for IMG in ${{ inputs.images }} ; do
+          IMG_NAME=$(echo "${IMG}" | sed 's/[^=]*=//')
+          if [ -n "${{ inputs.image-override }}" ] ; then
+            IMG_NAME="${{ inputs.image-override }}"
+          fi
+          if grep "${IMG_NAME}" Tiltfile ; then
+            sed "s,\(FROM ${IMG_NAME}:\)[a-zA-Z0-9_.-]*,\\1${{ inputs.tag }}," < Tiltfile > Tiltfile.new
+            mv Tiltfile.new Tiltfile
+            touch /tmp/changed-depot
+        done
+        if [ -f /tmp/changed-depot ] ; then
+          echo "changed=true" >> "$GITHUB_OUTPUT"
+        fi
+    - name: Commit and push to depot
+      if: "${{ steps.update-depot.outputs.changed == 'true' }}"
+      working-directory: depot
+      run: |
+        COMMIT_MSG="Upgrade localk8s: [ ${THISREPO} -> ${{ inputs.tag }} ]"
+        git commit -m "${COMMIT_MSG}"
+        TRIES=0
+        # If git push fails, it's hopefully just a concurrent update that we can retry.
+        while ! git push ; do
+          TRIES=$(expr ${TRIES} + 1)
+          if [ "${TRIES}" -ge 5 ] ; then
+            break
+          fi
+          git pull
+          sleep 30
+        done
