Support pushing release Docker images to an additional repository (#94)

diff --git a/.github/workflows/docker.yaml b/.github/workflows/docker.yaml
--- a/.github/workflows/docker.yaml
+++ b/.github/workflows/docker.yaml
@@ -15,6 +15,11 @@ on:
         description: Image base name, without tag.
         type: string
         required: true
+      additional_release_image_name:
+        description: An optional second image base name. If provided, all release tags will be applied and pushed here as well. Will not push pre-release or PR builds.
+        type: string
+        required: false
+        default: ""
       build_command:
         description: Command to run to build docker image. `${DOCKER_FULL_NAME}` should be used as the tag name.
         type: string
@@ -83,6 +88,7 @@ jobs:
       tags: ${{ steps.tag.outputs.tags }}
       longtag: ${{ steps.tag.outputs.longest }}
       runners: ${{ steps.archs.outputs.runners }}
+      prerelease: ${{ steps.name.outputs.prerelease }}
     steps:
       - name: Set docker image tags
         id: tag
@@ -127,13 +133,16 @@ jobs:
         id: name
         run: |
           DOCKER_IMAGE="${{ inputs.image_name }}"
+          PRERELEASE=false
           # If any tags look like prereleases, then we'll push our final image to our internal registry, not the public one.
           for TAG in ${{ steps.tag.outputs.tags }} ; do
             if ! [[ ${TAG} =~ ^[0-9.]*$ ]] ; then
               DOCKER_IMAGE="$(echo ${DOCKER_IMAGE} | sed 's/ironcore-images/ironcore-dev-1/')"
+              PRERELEASE=true
             fi
           done
           echo "name=${DOCKER_IMAGE}" >> "$GITHUB_OUTPUT"
+          echo "prerelease=${PRERELEASE}" >> "$GITHUB_OUTPUT"
       - name: Output docker image identifiers
         id: images
         run: |
@@ -233,6 +242,7 @@ jobs:
           EOF
           gcloud auth activate-service-account --key-file .github/gcloud-auth.json
           gcloud auth configure-docker --quiet
+          gcloud auth configure-docker us-docker.pkg.dev --quiet
       - name: Get canonical image name
         id: name
         run: |
@@ -272,6 +282,18 @@ jobs:
           clamscan /tmp/docker.tar
       - name: Push it!
         run: docker push "${{ steps.name.outputs.canonical }}-${{ steps.arch.outputs.arch }}"
+      - name: Tag and push additional image
+        if: inputs.additional_release_image_name != '' && needs.image.outputs.prerelease == 'false'
+        run: |
+          SRC="${{ steps.name.outputs.canonical }}-${{ steps.arch.outputs.arch }}"
+          if [[ "$SRC" != "${{ inputs.image_name }}:"* ]]; then
+              echo "Error: Canonical image name $SRC does not start with ${{ inputs.image_name }}."
+          exit 1
+          fi
+          # replace the base image name with the additional image name
+          DST=$(echo "$SRC" | sed "s#^${{ inputs.image_name }}:#${{ inputs.additional_release_image_name }}:#")
+          docker tag "$SRC" "$DST"
+          docker push "$DST"
       - name: Container hash
         id: container-hash
         run: |
@@ -323,36 +345,62 @@ jobs:
           EOF
           gcloud auth activate-service-account --key-file .github/gcloud-auth.json
           gcloud auth configure-docker --quiet
+          gcloud auth configure-docker us-docker.pkg.dev --quiet
       - name: Get canonical image name
         id: name
         run: echo "canonical=$(echo ${{ needs.image.outputs.images }} | sed 's/ .*//')" >> "$GITHUB_OUTPUT"
       - name: Create and push manifest
         run: |
           set -x
-          IMGS=$(echo ${{ inputs.archs }} | tr ' ' '\n' | sed 's%^%${{ steps.name.outputs.canonical }}-%' | tr '\n' ' ')
-          # Sometimes GCR gives random errors. Let's try a few times before giving up.
-          for RETRY in $(seq 10) ; do
-            for ARCH in ${{ inputs.archs }} ; do
-              if ! docker pull "${{ steps.name.outputs.canonical }}-${ARCH}" ; then
-                echo "Attempt #${RETRY} failed."
-                sleep 10
-                # Continue the outer loop, not the inner one.
-                continue 2
+          # Will look like "gcr.io/ironcore-dev-1/ironcore-id-server:1.2.6"
+          CANONICAL="${{ steps.name.outputs.canonical }}"
+          # Will look like "gcr.io/ironcore-dev-1/ironcore-id-server:1.2.6-amd64 gcr.io/ironcore-dev-1/ironcore-id-server:1.2.6-arm64"
+          IMGS=$(echo "${{ inputs.archs }}" | tr ' ' '\n' | sed "s%^%$CANONICAL-%" | tr '\n' ' ')
+          test_manifest_creation() {
+            local target="$1"
+            for RETRY in $(seq 10); do
+              echo "Attempt #$RETRY to pull images and create manifest for $target"
+              # Not quoting around '${{ inputs.archs }}' as we're relying on it being space-separated
+              for ARCH in ${{ inputs.archs }} ; do
+                if ! docker pull "${CANONICAL}-${ARCH}" ; then
+                  echo "Attempt #${RETRY} failed."
+                  sleep 10
+                  # Continue the outer loop, not the inner one.
+                  continue 2
+                fi
+              done
+              if docker manifest create "$target" ${IMGS} ; then
+                # We'll re-create this below, in the loop.
+                docker manifest rm "$target" || true
+                return 0
               fi
+              echo "Attempt #${RETRY} failed."
+              sleep 10
             done
-            if docker manifest create "${{ steps.name.outputs.canonical }}" ${IMGS} ; then
-              # We'll re-create this below, in the loop.
-              docker manifest rm "${{ steps.name.outputs.canonical }}"
-              break
-            fi
-            echo "Attempt #${RETRY} failed."
-            sleep 10
-          done
+            echo "ERROR: Unable to create manifest for $target after 10 attempts"
+            return 1
+          }
+
+          test_manifest_creation "$CANONICAL"
           # If that worked, we should be able to create each of the aliases (e.g. 4.12.0, 4.12, 4).
           for IMAGE in ${{ needs.image.outputs.images }} ; do
+            # Not quoting around IMGS as we're relying on it being space-separated
             docker manifest create "$IMAGE" ${IMGS}
             docker manifest push "$IMAGE"
           done
+
+          # Do the same for any additional manifests
+          if [ -n "${{ inputs.additional_release_image_name }}" ] && [ "${{ needs.image.outputs.prerelease }}" = "false" ]; then
+            CANONICAL=$(echo "$CANONICAL" | sed "s#^${{ inputs.image_name }}#${{ inputs.additional_release_image_name }}#")
+            test_manifest_creation "$CANONICAL"
+            IMGS=$(echo "${{ inputs.archs }}" | tr ' ' '\n' | sed "s%^%$CANONICAL-%" | tr '\n' ' ')
+            NEEDS_IMAGES=$(echo "${{ needs.image.outputs.images }}" | sed "s#${{ inputs.image_name }}:#${{ inputs.additional_release_image_name }}:#g")
+            for IMAGE in $NEEDS_IMAGES ; do
+              # Not quoting around IMGS as we're relying on it being space-separated
+              docker manifest create "$IMAGE" ${IMGS}
+              docker manifest push "$IMAGE"
+            done
+          fi
       # This triggers the Deploy workflow's `release: released`
       - name: Mark GitHub release as not prerelease
         if: github.event.release != null && inputs.update_github_release
